//Code Blue Types
export const SET_CPR_TIME_STATE = "SET_CPR_TIME_STATE";
export const SET_CODE_LOG_STATE = "SET_CODE_LOG_STATE";
export const SET_CODE_NAV_STATE = "SET_CODE_NAV_STATE";
export const SET_CODE_TIMER_STATE = "SET_CODE_TIMER_STATE";
